### ISSUE TITLE
Optimization as a fallback is not a good idea

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaProfileFitting.jl#16]
### Description

There are conditions that ensure that `x` can be found. If those conditions are not met, then the optimization algorithm is also not necessary.

For continuity on $x \to 0^+$, I am defining the problem as finding $x$ such that $P(x) = \mu$, if possible, where

$$S(x) = \frac{1}{|P|} \sum_{p \in P:\ p > 0} p^x.$$

This removes the $p = 0$ values, so we don't have $0^0$.

Assuming that the `profile_values` are in the interval $[0, 1]$, then we can verify that there is a solution for the mean equals $\mu$ with the following:

```
num_values = length(profile_values)
num_nonzeros = count(profile_values .> 0)
num_ones = count(profile_values .== 1)
has_solution = num_ones < mu * num_values <= num_nonzeros
```

If there is a solution, we can use root-finding. Notice that we need to find a proper interval, which the current code doesn't do. But this is easy to do.

If $\mu$ is larger than `num_nonzeros / num_values`, then choosing $x = 0$ is the best we can do.

If $\mu$ is smaller than `num_ones / num_values`, then the "solution" would be $x \to \infty$. Using optimization here won't help, because the only thing that the optimization method does is increase x until the derivative is close enough to zero. The mean value just approaches `num_ones / num_values`, so we can choose a reasonably large `x` and skip using the optimizer at all.

There are more details in this notebook: https://gist.github.com/abelsiqueira/de2e8deeafdc9641cd0982217b2ffe46

### Reproduction steps

```bash
No steps.
```

**Comment by datejada** [comment]
What a master class! 👏 👏 Thank you so much. I have double-checked with the values in the test folder. I get no solution for those values when using the `find_zero` function with the current implementation and $\mu = 0.4$ (The chances are that I was using the function wrong). But, with your proposal, I got the solution for that target, too, and it is more elegant with all the explanations and examples.
I'll update the code with your proposal and reuse most of the information in the Pluto notebook if you don't mind.
@g-moralesespana, any extra thoughts?

**Comment by g-moralesespana** [comment]
Indeed what a masterclass. So if there are no cases where optimization fits better, then there is no need for optimization at all. Nice @abelsiqueira, you are helping us to find better, simpler and faster solutions for our problems.
