### ISSUE TITLE
Create stable documentation

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaProfileFitting.jl#27]
### Description

You need to follow step 4 of COPIERTemplate:

> Create a DOCUMENTER_KEY, which will be used by for documentation purposes.
```
pkg> activate --temp
pkg> add DocumenterTools
julia> using DocumenterTools
julia> DocumenterTools.genkeys(user="UserName", repo="PackageName.jl")
```

> Follow the instruction in the terminal.

Otherwise, it doesn't get pushed successfully after tag bot.

**Comment by datejada** [comment]
Hi @abelsiqueira, I have followed the steps. It seems all of it is set in the repo now. Is there a way to test it?

**Comment by abelsiqueira** [comment]
I would test by creating a release.

**Comment by abelsiqueira** [comment]
There is something else going on, because the Docs workflow is not running when tags are created. Maybe there is something else missing, but I am not sure yet.
